### ISSUE TITLE
Commands out of sync

### ISSUE THREAD

**Issue by KierenConnell** [vsc55/ombi_sqlite_mysql#15]
I'm trying to migrate to MySQL (Running Windows)

Got everything ready to go, when I run the ombi_sqlite2mysql_multi.py it throws an error telling me commands are out of sync
Looking at the output, it's trying to conver the Settings Database first, but looking at the github wiki it should be doing the Ombi database first

Any idea what the issue might be? The only thing I've done to the .py is change the filepath

https://pastebin.com/abbnsxTH
This is the output I'm getting when ombi_sqlite2mysql_multi.py is run

**Comment by vsc55** [comment]
Hi @KierenConnell,
The order of the databases may change as it depends on the order in which they are defined in the "migration.json" file.
Have you checked if the tables have been created correctly after doing step number **3 Create and prepare tables**?
https://github.com/vsc55/ombi_sqlite_mysql#3-create-and-prepare-tables

**Comment by KierenConnell** [comment]
Hi @vsc55,

When I run `python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --only_db_json --host 192.168.1.9 --db Ombi --user ombi --passwd ombi`

It creates a database.json file with all 3 Ombi databases pointing to the same Ombi database

database.json output
`{"SettingsDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}, "OmbiDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}, "ExternalDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}}`

Is this correct?

I think I also missed the step whereby after running this, I need to start Ombi, then stop, THEN do the data migration.
Is that correct?

**Comment by KierenConnell** [comment]
So, currently my database.json and database_multi.json file both look like so

```
{
  "OmbiDatabase": {
    "Type": "MySQL",
    "ConnectionString": "Server=localhost;Port=3306;Database=Ombi;User=ombi;Password=ombi"
  },
  "SettingsDatabase": {
    "Type": "MySQL",
    "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"
  },
  "ExternalDatabase": {
    "Type": "MySQL",
    "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"
  }
}
```

I started Ombi up, and the databases in MySQL were populated with a bunch of different tables
Stopped Ombi

And now I get the following output

```
C:\Python27>python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Traceback (most recent call last):
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1148, in <module>
    main()
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1106, in main
    _mysql_database_json_update(True)
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1003, in _mysql_database_json_update
    "ConnectionString": "Server={0};Port={1};Database={2};User={3};Password={4}".format(mysql_cfg['host'], mysql_cfg['port'], mysql_cfg['db'], mysql_cfg['user'], mysql_cfg['passwd'])
TypeError: 'NoneType' object has no attribute '__getitem__' 
```

**Comment by vsc55** [comment]
> 
> 
> So, currently my database.json and database_multi.json file both look like so
> 
> ```
> {
>   "OmbiDatabase": {
>     "Type": "MySQL",
>     "ConnectionString": "Server=localhost;Port=3306;Database=Ombi;User=ombi;Password=ombi"
>   },
>   "SettingsDatabase": {
>     "Type": "MySQL",
>     "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"
>   },
>   "ExternalDatabase": {
>     "Type": "MySQL",
>     "ConnectionString": "Server=localhost;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"
>   }
> }
> ```
> 
> I started Ombi up, and the databases in MySQL were populated with a bunch of different tables
> Stopped Ombi
> 
> And now I get the following output
> 
> ```
> C:\Python27>python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi
> Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55
> 
> Traceback (most recent call last):
>   File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1148, in <module>
>     main()
>   File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1106, in main
>     _mysql_database_json_update(True)
>   File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1003, in _mysql_database_json_update
>     "ConnectionString": "Server={0};Port={1};Database={2};User={3};Password={4}".format(mysql_cfg['host'], mysql_cfg['port'], mysql_cfg['db'], mysql_cfg['user'], mysql_cfg['passwd'])
> TypeError: 'NoneType' object has no attribute '__getitem__' 
> ```

Hi @KierenConnell,
A very important thing in step number 3 when creating all the tables correctly is after starting ombi, access the web before stopping ombi. Otherwise not all tables will be created correctly.

If your mysql server is 192.168.1.9 the steps would be:
Note: Before starting the process, check that the Ombi database is empty.

1. `python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --only_db_json --host 192.168.1.9 --db Ombi --user ombi --passwd ombi`
2. Start Ombi
3. Access Web Ombi (no need to do anything on the web, just load)
4. Stop Ombi
5. `python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi`

**Comment by KierenConnell** [comment]
> 
> Hi @KierenConnell,
> A very important thing in step number 3 when creating all the tables correctly is after starting ombi, access the web before stopping ombi. Otherwise not all tables will be created correctly.
> 
> If your mysql server is 192.168.1.9 the steps would be:
> Note: Before starting the process, check that the Ombi database is empty.
> 
> 1. `python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --only_db_json --host 192.168.1.9 --db Ombi --user ombi --passwd ombi`
> 2. Start Ombi
> 3. Access Web Ombi (no need to do anything on the web, just load)
> 4. Stop Ombi
> 5. `python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi`

@vsc55 
When I run the first python command, the database.json file it creates is like this.

`{"SettingsDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}, "OmbiDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}, "ExternalDatabase": {"ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi", "Type": "MySQL"}}`

Is it correct that in the database.json file, all 3 databases should be pointing to the same Ombi database?
When running step 5 (As above) will the migration process split out my Ombi.db, OmbiExternal.db and OmbiSettings.db into the MySQL equivalents? (i.e the Ombi.db will migrate to the Ombi database in MySQL, the OmbiSettings.db will migrate to the OmbiSettings database in MySQL?)

**Comment by vsc55** [comment]
Hi @KierenConnell,
By default, the normal thing is that all the tables are in the same mysql database, so it is normal that in "database.json" they point to the same database.

Try again, but before you start check that in "C:\Plex\Ombi" the files "database.json", "database_multi.json" or "migration.json" do not exist and if they exist delete them.

**Comment by KierenConnell** [comment]
> Hi @KierenConnell,
> By default, the normal thing is that all the tables are in the same mysql database, so it is normal that in "database.json" they point to the same database.
> 
> Try again, but before you start check that in "C:\Plex\Ombi" the files "database.json", "database_multi.json" or "migration.json" do not exist and if they exist delete them.

@vsc55 
I'm getting further in the process!
I managed to get the migration tool to start running, it successfully dumped out the SQLite databases, but then I got this output error

```
C:\Python27>python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [Ô£ô]

MySQL > Connecting... [Ô£ô]
- Reading   [############################################################] 1/1
Read tables [Ô£ô]

Check migration.json:
- SettingsDatabase [SQLite >> Migrate]
- OmbiDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- SettingsDatabase  [############################################################] 24/24
- OmbiDatabase      [############################################################] 748/748
- ExternalDatabase  [############################################################] 31705/31705

Start clean tables:

* MySQL Error [2014]: Commands out of sync; you can't run this command now
* Error Query: EXECUTE s; DEALLOCATE PREPARE s;

Traceback (most recent call last):
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1148, in <module>
    main()
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 1122, in main
    if _mysql_tables_clean():
  File "C:\Plex\Ombi\ombi_sqlite2mysql.py", line 674, in _mysql_tables_clean
    for table, count in return_query[1]:
TypeError: 'NoneType' object is not iterable
```

Any idea what this might be caused by?

**Comment by vsc55** [comment]
Are you using python2?
If so, can you try python3 to see if it gives you the same error?

**Comment by KierenConnell** [comment]
> Are you using python2?
> If so, can you try python3 to see if it gives you the same error?

Looks like it's working with python 3.8, but I'm getting a TON of errors saying that 'Table 'ombi.plexservercontent' doesn't exist
Looks like I'm going to get about 32,000 of them

Any ideas?

**Comment by vsc55** [comment]
This is because after starting ombi and accessing the web, ombi has stopped very quickly and has not had time to create all the tables.

Try this:
1. Remove all the tabals from the database mysql.
2. Start Ombi
3. Access Web Ombi (no need to do anything on the web, just load)
4. Wait a minute for all the tables to be created correctly and then stop ombi.
5. python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi

**Comment by KierenConnell** [comment]
> This is because after starting ombi and accessing the web, ombi has stopped very quickly and has not had time to create all the tables.
> 
> Try this:
> 
> 1. Remove all the tabals from the database mysql.
> 2. Start Ombi
> 3. Access Web Ombi (no need to do anything on the web, just load)
> 4. Wait a minute for all the tables to be created correctly and then stop ombi.
> 5. python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi

I'll give that a try. Quite strange because I could see it creating the tables in the database, and I left Ombi running for about 5mins after I opened the webpage.
I was also using Python 2.7 the first time, so that might have been the issue.

Do you know how many tables are supposed to be in each database?

**Comment by vsc55** [comment]
I don't know how many are in each database.
I just looked and I have 44 tables on the mysql server.
And I would use python3.

**Comment by KierenConnell** [comment]
@vsc55 

Okay, I think I see what the issue might be, but not sure how to resolve it.
It looks like all the tables are created now.
The error that was being thrown before was 
```
- Running   [###.........................................................] 1865/32397
* MySQL Error [1146]: Table 'ombi.plexservercontent' doesn't exist
* Error Query: INSERT INTO `PlexServerContent` (`Id`, `Title`, `ReleaseYear`, `ImdbId`, `TvDbId`, `TheMovieDbId`, `Type`, `Url`, `Key`, `AddedAt`, `Quality`, `RequestId`) VALUES(15942,'Little Nicky','2000','tt0185431','2447','9678',0,'https://app.plex.tv/web/app#!/server/7b45dd5b43d8b43d8ec979f9a7cbe9242c37b69b/details?key=library%2Fmetadata%2F37588',37588,'2020-11-17 02:00:43.4118484','1080',NULL);
```

But manually browsing, I can see that the plexservercontent table is actually in ombi_external
But the error seems to indicate it's trying to find it in the ombi database.

**Comment by vsc55** [comment]
What version of ombi are you using?
And what does the database.json file contain?

**Comment by KierenConnell** [comment]
@vsc55 

Ombi V4
~~Can't remember which minor release, but it's within the last few weeks~~
I just finished moving Ombi to 4.0.721 and I'm getting the same errors, 

```
C:\Users\Administrator\AppData\Local\Programs\Python\Python38>python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --only_db_json --host 192.168.1.9 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [✓]


C:\Users\Administrator\AppData\Local\Programs\Python\Python38>python C:\Plex\Ombi\ombi_sqlite2mysql.py -c C:\Plex\Ombi --host 192.168.1.9 --db Ombi --user ombi --passwd ombi
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (C:\Plex\Ombi\database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [############################################################] 1/1
Read tables [✓]

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 748/748
- SettingsDatabase  [############################################################] 24/24
- ExternalDatabase  [############################################################] 31705/31705

Start clean tables:
- [CLEAN ] -> aspnetusers -> rows: 1
- [CLEAN ] -> notificationtemplates -> rows: 100
- [CLEAN ] -> __efmigrationshistory -> rows: 6

- Running   [############################################################] 3/3
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 32490/32490
- Running   [#...........................................................] 697/32397
* MySQL Error [1146]: Table 'ombi.applicationconfiguration' doesn't exist
* Error Query: INSERT INTO `ApplicationConfiguration` (`Id`, `Type`, `Value`) VALUES(1,1,'http://*:5000');

- Running   [#...........................................................] 719/32397
* MySQL Error [1146]: Table 'ombi.plexservercontent' doesn't exist
* Error Query: INSERT INTO `PlexServerContent` (`Id`, `Title`, `ReleaseYear`, `ImdbId`, `TvDbId`, `TheMovieDbId`, `Type`, `Url`, `Key`, `AddedAt`, `Quality`, `RequestId`) VALUES(14796,'The Addams Family','1991','tt0101272','2475','2907',0,'https://app.plex.tv/web/app#!/server/7b45dd5b43d8b43d8ec979f9a7cbe9242c37b69b/details?key=library%2Fmetadata%2F28272',28272,'2020-11-16 12:30:03.5113829','1080',NULL);
```

![image](https://user-images.githubusercontent.com/46445781/99889764-474a7580-2c50-11eb-9ef9-1362e2e49ea0.png)
The two tables it references as not existing, definitely do exist. Just, in Ombi_External and Ombi_Settings instead of Ombi


database.json
`{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}`

database_multi.json
`{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}`

**Comment by vsc55** [comment]
Try this:
1. Remove all tables database mysql
2. Check:
database.json
{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}

database_multi.json
{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=192.168.1.9;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}

3. Star Ombi
4. Open Web Ombi
5. Stop Ombi
6. python ombi_sqlite2mysql_multi.py -c  C:\Plex\Ombi

And better to use python3
