### ISSUE TITLE
Issues with migrating to MYSQL

### ISSUE THREAD

**Issue by VideoScape** [vsc55/ombi_sqlite_mysql#16]
Hey there thought I would start the process of moving ombi away from sqlite and to mysql but it seems I have hit some issues with it

> [root@titan ombi_sqlite_mysql]# python3 ombi_sqlite2mysql.py -c /opt/ombi --host ****** --db ombi --user root --passwd ******* --force
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (/opt/ombi/database.json)... [✓]

MySQL > Connecting... [✓]
Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 7373/7373
- SettingsDatabase  [############################################################] 28/28
- ExternalDatabase  [############################################################] 7190/7190

Start clean tables:

* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL' at line 1
* Error Query: EXECUTE s; DEALLOCATE PREPARE s;

Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1150, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1122, in main
    if _mysql_tables_clean():
  File "ombi_sqlite2mysql.py", line 674, in _mysql_tables_clean
    for table, count in return_query[1]:
TypeError: 'NoneType' object is not iterable

[root@titan ombi_sqlite_mysql]# python3 ombi_sqlite2mysql.py -c /opt/ombi --host ***** --db ombi --user root --passwd ******* 
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (/opt/ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [............................................................] 0/1
- Error: Table "{0}" requiered is not exist in the server MySQL!!!
Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1150, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1111, in main
    if not _fix_insert_read_mysql():
  File "ombi_sqlite2mysql.py", line 932, in _fix_insert_read_mysql
    print("- Error: Table \"{0}\" requiered is not exist in the server MySQL!!!").format(k)
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by vsc55** [comment]
Hi @VideoScape,
No need to add "--force".
I would try to start the process again.
Delete all the tables from the database and then try this:
```
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
$ /opt/ombi/ombi --migrate
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
```
Replace host, db, user pass with those of your system and replace "/etc/Ombi" with the location where you have the sqlite databases stored.

**Comment by VideoScape** [comment]
Hi I cannot do /opt/ombi/ombi --migrate as I am using docker version of ombi, running it within /app. but it seems it does not recognize it, 

[root@titan ombi_sqlite_mysql]# python3 ombi_sqlite2mysql.py -c /opt/ombi --host **** --db Ombi --user root --passwd ******
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (/opt/ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [............................................................] 0/1
- Error: Table "{0}" requiered is not exist in the server MySQL!!!
Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1150, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1111, in main
    if not _fix_insert_read_mysql():
  File "ombi_sqlite2mysql.py", line 932, in _fix_insert_read_mysql
    print("- Error: Table \"{0}\" requiered is not exist in the server MySQL!!!").format(k)
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by VideoScape** [comment]
I deleted Ombi and then followed 
CREATE DATABASE IF NOT EXISTS `Ombi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
To create a new one looking in phpmyadmin it is empty

**Comment by vsc55** [comment]
Try this:
```
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
$ docker exec -it <container_id_or_name> /opt/ombi/ombi --migrate
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
```
Replace "/etc/Ombi" with the location where docker stores the sqlite databases. 

You can also log into docker with bash: 
`docker exec -it <container_id_or_name> /bin/bash`

Make sure you have the latest version of ombi before starting the migration.

**Comment by VideoScape** [comment]
Hey, yeah i got the latest version, made sure to pull it down, here is what came out, its a bit long so have a look here
https://pastebin.com/8pDcaMkR

**Comment by VideoScape** [comment]
https://pastebin.com/8pDcaMkR

**Comment by vsc55** [comment]
Are you using version 3 or 4 of ombi? 

Run the following command to see the exact version. 
`docker exec -it <container_id_or_name> /opt/ombi/ombi --version`

**Comment by VideoScape** [comment]
Looks like i am running  3.0.5223
the image i am using is hotio/ombi:latest but to get 4.0 it seems to be hotio/ombi:testing

**Comment by vsc55** [comment]
I would advise you to first migrate to version 4 and then do the migration.
The problem is that "--migrate" has been implemented in version 4. 

For version 3 you would have to do this procedure:
1. Run: `$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi`
2. Start docker.
3. Access the ombi website so that all the tables are created (wait a minute for all the tables to be created).
4. Stop docker. 
5. Run: `$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi`

I am using linuxserver/ombi:development

**Comment by VideoScape** [comment]
Ah, i have upgraded now and used ombi for a few to see how everything works but this still seems to happen, 

Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [SQLite >> Migrate]

Dump SQLite:
- OmbiDatabase      [############################################################] 7387/7387
- SettingsDatabase  [############################################################] 28/28
- ExternalDatabase  [############################################################] 7191/7191

Start clean tables:
- [CLEAN ] -> ApplicationConfiguration -> rows: 2
- [BACKUP] -> __EFMigrationsHistory
- [SKIP  ] -> __EFMigrationsHistory -> rows: 1

- Running   [############################################################] 3/3
Clean tables [✓]

Start Migration:
- Preparing [############################################################] 14619/14619
- Running   [............................................................] 0/14517
* MySQL Error [1146]: Table 'Ombi.AspNetUsers' doesn't exist
* Error Query: INSERT INTO `AspNetUsers` (`Id`, `UserName`, `NormalizedUserName`, `Email`, `NormalizedEmail`, `EmailConfirmed`, `PhoneNumber`, `PhoneNumberConfirmed`, `TwoFactorEnabled`, `LockoutEnd`, `LockoutEnabled`, `AccessFailedCount`, `Alias`, `UserType`, `ProviderUserId`, `LastLoggedIn`, `MovieRequestLimit`, `EpisodeRequestLimit`, `MusicRequestLimit`, `UserAccessToken`, `PasswordHash`, `SecurityStamp`, `ConcurrencyStamp`, `Language`, `StreamingCountry`) VALUES('d853fbe4-c64f-496e-80fb-920d3b7af005','Api','API',NULL,NULL,0,NULL,0,0,NULL,0,0,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'4a01c126-86e2-4f48-8840-ccb0726852d2',NULL,'US');

**Comment by vsc55** [comment]
Now that you have the latest version delete all the tables from the mysql database and start the process again: 
```
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
$ docker exec -it <container_id_or_name> /opt/ombi/ombi --migrate
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
```

**Comment by VideoScape** [comment]
I get this error once I have dropped the database and recreated it empty using the sql in the wiki

Migration tool from SQLite to MySql/MariaDB for ombi (3.0.4) By VSC55

Generate file "database.json":
- Saving in (/opt/ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [............................................................] 0/1
- Error: Table "{0}" requiered is not exist in the server MySQL!!!
Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1150, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1111, in main
    if not _fix_insert_read_mysql():
  File "ombi_sqlite2mysql.py", line 932, in _fix_insert_read_mysql
    print("- Error: Table \"{0}\" requiered is not exist in the server MySQL!!!").format(k)
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by vsc55** [comment]
Ok, I think I already know why it fails.
Look in the database if there is any table created, I suppose not, if it exists delete them. 

Run:
```
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
$docker exec -it <container_id_or_name> /opt/ombi/ombi --storage /config --migrate
$ python3 ombi_sqlite2mysql.py -c /etc/Ombi --host 192.168.1.100 --db Ombi --user ombi --passwd ombi
```
We have to add the --storage parameter so that it uses the correct configuration files.

**Comment by VideoScape** [comment]
Looks like it created some tables in the DB but still kinda the same thing

https://pastebin.com/me4pJv5u

**Comment by vsc55** [comment]
```
Unhandled exception. MySqlConnector.MySqlException (0x80004005): Specified key was too long; max key length is 767 bytes
 ---> MySqlConnector.MySqlException (0x80004005): Specified key was too long; max key length is 767 bytes
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)
   at MySqlConnector.MySqlDataReader.ActivateResultSet()
   at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken)
```
This looks like an ombi glitch when creating the tables.

**Comment by VideoScape** [comment]
Can you think of any workaround for this?

**Comment by vsc55** [comment]
@VideoScape are you still using docker hotio/ombi:testing? 

**Update:**
It seems to be a mysql not an ombi problem. 
https://bugs.mysql.com/bug.php?id=81817

Same problem, it seems that you have a very old version of mysql: 
https://github.com/Ombi-app/Ombi/issues/3254

**Comment by VideoScape** [comment]
Hey, yeah i was using that, i can change images to the linuxserver one and my mysql version is 
mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by vsc55** [comment]
Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1?
The server has to be either MySQL or MariaDB but not both at the same time.

From what looks like ombi uses "Pomelo.EntityFrameworkCore.MySql" and is compatible with these versions of mysql: 
    MySQL 8.0
    MySQL 5.7
    MariaDB 10.5
    MariaDB 10.4
    MariaDB 10.3
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#supported-dbms-and-versions

**Comment by VideoScape** [comment]
yeah its mariadb, interesting that it does not support newer versions,  i guess i could downgrade?

**Comment by vsc55** [comment]
Won't your version be 5.5.68? It cannot be 15.1 since according to the mariadb website the latest version is 10.5.9. 
https://mariadb.com/kb/en/release-notes/
I use version 10.3.21-MariaDB and it works without problem.

**Comment by VideoScape** [comment]
Oh interesting find, yeah looking at PMA it is 5.5.68-MariaDB - MariaDB Server, I will go ahead and update and come back here with the findings, interestingly that server has been recently installed so I guess i install an old repo

**Comment by VideoScape** [comment]
Ah perfect, yeah upgrading mariadb from 5.5.68 to  10.5.8, and reran the commands reworked on yesterday, it now runs perfectly.

Thank you for all the help!
