### ISSUE TITLE
Error: Table "__EFMigrationsHistory" requiered is not exist in the server MySQL!!!

### ISSUE THREAD

**Issue by RosiersRobin** [vsc55/ombi_sqlite_mysql#25]
Followed all the steps, getting the following output:

```
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/etc/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
- Reading   [............................................................] 0/1
- Error: Table "__EFMigrationsHistory" requiered is not exist in the server MySQL!!!
Read tables [!!]

MySQL > Disconnecting... [✓]
```

What am I doing wrong here?

The --force gives this;

```
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/etc/Ombi/database.json)... [✓]

MySQL > Connecting... [✓]
Check migration.json:
- OmbiDatabase [SQLite >> Migrate]
- SettingsDatabase [SQLite >> Migrate]
- ExternalDatabase [No Config >> Skip]

Dump SQLite:
- OmbiDatabase      [############################################################] 9/9
- SettingsDatabase  [############################################################] 13/13

Start clean tables:

* MySQL Error [1064]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
* Error Query: EXECUTE s; DEALLOCATE PREPARE s;

Traceback (most recent call last):
  File "ombi_sqlite2mysql.py", line 1250, in <module>
    main()
  File "ombi_sqlite2mysql.py", line 1221, in main
    if _mysql_tables_clean():
  File "ombi_sqlite2mysql.py", line 741, in _mysql_tables_clean
    for table, count in return_query[1]:
TypeError: 'NoneType' object is not iterable
```

**Comment by vsc55** [comment]
Hi @RosiersRobin,

It may be a problem with the mysql library.
If you are using debian/ubuntu, try this:
```bash
$ apt-get remove python3-mysqldb
$ pip3 install mysqlclient
```

It may also be that you must specify the path where the json files and sqlite databases are when creating the databases.
Try the following command:
```bash
$ /opt/ombi/Ombi --migrate --storage /etc/Ombi
```
In the example above I assume that your database.json file and sqlite databases are in /etc/Ombi.

**Comment by RosiersRobin** [comment]
Hi,


I didn't get an error now, however, I don't see any data from the SQLITE in the Mysql db...

**Comment by vsc55** [comment]
Hi,
What OS are you using?
Where do you have Ombi installed?
Where do you have the json configuration files and sqlite databases?

**Comment by RosiersRobin** [comment]
Hi,

Latest ubuntu version,

Application Base Path: /opt/Ombi
All files are normally in there to;

![image](https://user-images.githubusercontent.com/5263188/163730149-2cf54781-c392-4463-924f-e1d5c68b7b9a.png)

**Comment by vsc55** [comment]
I see that the *.db databases are in /opt/Ombi.
Try removing all the tables from the database and start the process again, but using /opt/Ombi as the configuration path.

```bash
# python ombi_sqlite2mysql.py -c /opt/Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
# Ombi.exe --migrate --storage /opt/Ombi
# python ombi_sqlite2mysql.py -c /opt/Ombi --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
```

You can confirm the path where the databases are stored if you access ombi and go to "Settings> System > About".
![imagen](https://user-images.githubusercontent.com/13438676/163730361-66b993f1-7352-4dcc-93fa-89378d12d9dd.png)

**Comment by RosiersRobin** [comment]
That worked like a charm!

Maybe an idea for combvining the commands into 1?

thanks already!
