### ISSUE TITLE
Multi fails with Decimal Conversion error

### ISSUE THREAD

**Issue by Tripwyr** [vsc55/ombi_sqlite_mysql#26]
I followed the steps here but got an error at step 4.2: https://docs.ombi.app/guides/migrating-databases/

Environment:
Ombi 4.16.11
MariaDB 10.5.15
Ombi in Docker using linuxserver/ombi:latest

I ran the command:
python3 ombi_sqlite2mysql_multi.py -c /config

And got this output:
```
root@466a7ceaa57c:/ombi_sqlite_mysql# python3 ombi_sqlite2mysql_multi.py -c /config
Migration tool from SQLite to Multi MySql/MariaDB for ombi (1.0.3) By VSC55

- Processing DataBase (OmbiDatabase)...
  -------------------

- Saving in (/config/migration.json)... [✓]
Generate file "database.json":
- Saving in (/config/database.json)... [✓]

MySQL > Connecting... [✓]
Traceback (most recent call last):
  File "ombi_sqlite2mysql_multi.py", line 328, in <module>
    main()
  File "ombi_sqlite2mysql_multi.py", line 269, in main
    ombi_sqlite2mysql.main()
  File "/ombi_sqlite_mysql/ombi_sqlite2mysql.py", line 1208, in main
    _mysql_connect()
  File "/ombi_sqlite_mysql/ombi_sqlite2mysql.py", line 457, in _mysql_connect
    _mysql_get_lower_case_table_name()
  File "/ombi_sqlite_mysql/ombi_sqlite2mysql.py", line 618, in _mysql_get_lower_case_table_name
    return_query = _mysql_fetchall_querys(["show variables where variable_name = 'lower_case_table_names'"])
  File "/ombi_sqlite_mysql/ombi_sqlite2mysql.py", line 572, in _mysql_fetchall_querys
    cur.execute(q)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 321, in _query
    self._post_get_result()
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 355, in _post_get_result
    self._rows = self._fetch_row(0)
  File "/usr/local/lib/python3.6/dist-packages/MySQLdb/cursors.py", line 328, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by vsc55** [comment]
Hi @Tripwyr,
Do you want to export the sqlite databases to a single mysql database, or to several different databases? Since I see that you are using the multiscript.
Can you copy the contents of the database_multi.json file?

**Update:**
It could also be a problem with the mysql library, since apt-get usually installs a version that causes problems.
Try the following:
```bash
$ docker exec ombi bash
$ apt-get remove python3-mysqldb
$ pip3 install mysqlclient
$ python ombi_sqlite2mysql.py -c /config --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
$ Ombi.exe --migrate --storage /config
$ python ombi_sqlite2mysql.py -c /config --host 127.0.0.1 --db Ombi --user ombi --passwd ombi
```
This example is for a migration with a single database as the destination.

**Comment by Tripwyr** [comment]
Hello,

I have already installed mysqlclient through pip3. I am looking to export to multiple databases for ease of future management, yes.

Here is the database_multi.json:
cat database_multi.json
{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi_Settings;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi_External;User=ombi;Password=ombi"}}

I did notice that the script generates a database.json file, with these contents:
cat database.json
{"OmbiDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "SettingsDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi;User=ombi;Password=ombi"}, "ExternalDatabase": {"Type": "MySQL", "ConnectionString": "Server=172.22.200.92;Port=3306;Database=Ombi;User=ombi;Password=ombi"}}

Notably the Settings and External databases are defaulted back to Ombi instead of Ombi_Settings and Ombi_External

Update for the sake of being thorough:

root@466a7ceaa57c:/ombi_sqlite_mysql# apt-get remove python3-mysqldb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'python3-mysqldb' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libmysqlclient20 mysql-common
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@466a7ceaa57c:/ombi_sqlite_mysql# pip3 install mysqlclient
The directory '/config/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/config/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.6/dist-packages

Should I remove libmysqlclient20 and mysql-common?

**Comment by vsc55** [comment]
I have not tried it with docker, let's see if I have time and try it.
I'll let you know as soon as I know something.

**Comment by vsc55** [comment]
Hi @Tripwyr,
I have created a docker for the migration process, this would be the procedure.

We will have to prepare 2 folders:
- /dockers/ombi/config **(this is where we have our sqlite databases and configurations of our current ombi docker)**
- /dockers/ombi/ombi **(it is where we will download and unzip the version that we are using in the ombi docker)**
We can download the latest version from: https://github.com/Ombi-app/Ombi/releases

Before starting the process, if there is any table in our mysql/mariadb databases we will have to delete it.

```bash
docker run -v /dockers/ombi/config:/config -v /dockers/ombi/ombi:/opt/ombi -it vsc55/ombi_sqlite_mysql
root@d3f69ef2e75d:/opt/ombi_sqlite_mysql# python3 ombi_sqlite2mysql.py -c /config --only_db_json --host db --db Ombi --user ombi --passwd ombi
```
Now we edit the "database.json" file and configure the different databases.
```bash
root@d3f69ef2e75d:/opt/ombi_sqlite_mysql# ./migrate.sh
root@d3f69ef2e75d:/opt/ombi_sqlite_mysql# cp database.json database_multi.json
root@d3f69ef2e75d:/opt/ombi_sqlite_mysql# python3 ombi_sqlite2mysql_multi.py -c /config
```

And this should work.
I have tested it and it has worked without any problem.
