### ISSUE TITLE
Migration from sqlite to MariaDB on QNAP NAS

### ISSUE THREAD

**Issue by KevinBoone90** [vsc55/ombi_sqlite_mysql#27]
**Ombi Version:** Stable 4.16.12

**Operating System:** QTS

**Install Method:** docker

**Issue description:**
When running the conversion script from within the docker container (using /migrate per [Migrating Databases - Ombi Docs](https://docs.ombi.app/guides/migrating-databases/#6-faq)) I'm getting a SQL error.

/config folder contains : database.json / migration.json / Ombi.db + Settings and External

Managed to install Python 3 on the linux based system via SSH 

**Log file:**
[moya@NASflix Container]$ python3 ombi_sqlite2mysql.py -c --only_manager_json
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Error load MySQLdb, check if MySQLdb is installed!

**Comment by vsc55** [comment]
Hi @KevinBoone90,
You don't have a necessary python library installed.
```bash
pip3 install mysqlclient
pip3 install packaging 
```

There is also docker created for the migration process:
https://github.com/vsc55/ombi_sqlite_mysql/issues/26#issuecomment-1107862705
