### ISSUE TITLE
Python error while following steps to migrate database

### ISSUE THREAD

**Issue by roadhazard** [vsc55/ombi_sqlite_mysql#28]
I have Ombi 4.20.3 setup and running perfectly using SQLite. Decided to switch to MySQL and followed the steps and after issuing this command:

`
python ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host super-secret-ip --db Ombi --user super-secret-username --passwd super-secret-password
`

I get this back:

`
Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Python2 is not supported, use python3!
`

I'm a bit of a n00b with Linux. What am I messing up?  I have Python v2.7.18 installed as well as Python3 v3.9.2. I tried the same command with 'python3 ............' and got another error (forget....not home at the moment).

OS is Debian 11.3. This is my media server box and has Plex, Emby, Sonarr, NZBGet, Ombi and Radarr all working together with no problems. Pretty plain Jane setup.

**Comment by vsc55** [comment]
It looks like you don't have python3 installed on your system.

**Comment by roadhazard** [comment]
> It looks like you don't have python3 installed on your system.

I think it's installed?:

$ python3 -V

Python 3.9.2

sudo apt install python3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3 is already the newest version (3.9.2-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by vsc55** [comment]
If you run the following command, what error is produced exactly?

`python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host super-secret-ip --db Ombi --user super-secret-username --passwd super-secret-password`

**Comment by roadhazard** [comment]
> If you run the following command, what error is produced exactly?
> 
> `python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host super-secret-ip --db Ombi --user super-secret-username --passwd super-secret-password`

Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Error load MySQLdb, check if MySQLdb is installed!

**Comment by vsc55** [comment]
Hi @roadhazard,
That message is because you are missing some dependencies:


**Step 3.2**
https://github.com/vsc55/ombi_sqlite_mysql/blob/master/README.md
```bash
pip3 install mysqlclient
pip3 install packaging
```
