### ISSUE TITLE
Error switching to MySQLDB on dietpi

### ISSUE THREAD

**Issue by tellice** [vsc55/ombi_sqlite_mysql#29]
Trying to to switch to MySQL DB from Sqllte on DietPi v8.7.1, i have latest release of Ombi, python3 and MariaDB installed i run the command 

python ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host localhost --db Ombi --user ombi --passwd ombi

i changed the ip address to my raspberrypi

i get the following error

Error load MySQLdb, check if MySQLdb is installed!

MeariaDB server is running

what am i doing wrong?

**Comment by vsc55** [comment]
Hi @tellice ,
That message is because you are missing some dependencies:

Step 3.2
https://github.com/vsc55/ombi_sqlite_mysql/blob/master/README.md

pip3 install mysqlclient
pip3 install packaging

**Comment by tellice** [comment]
I have tried running them commands and i get the following error:

-bash: pip3: command not found

**Comment by tellice** [comment]
i have found the following command which installs the required packages:

apt update; apt install python3 python3-mysqldb -y;

now running the commands
cd ombi_sqlite_mysql
python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host localhost --db Ombi --user ombi --passwd ombi

Generates file "database.json" and saves it to /etc/ombi/database.json

i then run either
/opt/ombi/Ombi --migrate
or
/opt/ombi/Ombi --migrate --storage /etc/Ombi

and i get -base: /opt/ombi/ombi: No such file or directory

**Comment by tellice** [comment]
I got it to work, it was changing the case of /opt/ombi/Ombi to /opt/Ombi/Ombi

/opt/Ombi/Ombi --migrate

i have then ran
python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_manager_json
nano /etc/Ombi/migration.json

entered the following in the mirgration.json

{
   "OmbiDatabase": {
      "Type":"sqlite",
      "ConnectionString":"Data Source=/etc/Ombi/Ombi.db"
   },
   "SettingsDatabase": {
      "Type":"sqlite",
      "ConnectionString":"Data Source=/etc/Ombi/OmbiSettings.db"
   }
}

And run the finial command

python3 ombi_sqlite2mysql.py -c /etc/Ombi --host localhost --db Ombi --user ombi --passwd ombi

And i get the following:

Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Generate file "database.json":
- Saving in (/etc/Ombi/database.json)... [✓]

MySQL > Connecting... [!!]
* MySQL Error [1049]: Unknown database 'Ombi'

Which the Ombi.db is at that location

**Comment by vsc55** [comment]
Hi @tellice,
That "python3-mysqldb" package from apt usually gives problems.
Try running the following commands as reported in the update guide:
```bash
$ python3 -m pip install mysqlclient
$ python3 -m pip install packaging
```

You can also try to install pip with the following command:
```bash
$ apt-get install python3-pip
```

If all the dependencies are installed correctly, you will only have to execute these commands:
```bash
# python3 ombi_sqlite2mysql.py -c /etc/Ombi --only_db_json --host localhost --db Ombi --user ombi --passwd ombi
# /opt/ombi/Ombi --migrate
# python3 ombi_sqlite2mysql.py -c /etc/Ombi --host localhost --db Ombi --user ombi --passwd ombi
```

All this would be assuming that you have ombi installed in /opt/ombi and the databases in /etc/Ombi.
Keep in mind that linux distinguishes between uppercase and lowercase and depending on how you have it installed on your system this can change.

Also note that the error "MySQL Error [1049]: Unknown database 'Ombi'" is not related to Ombi.db, it is informing you that the database does not exist on your MySQL server.
Review step 2.1 of the migration guide:
https://github.com/vsc55/ombi_sqlite_mysql#21-a-single-database

**Comment by tellice** [comment]
Thank you thats migrated over and all working again now
