### ISSUE TITLE
mysqlclient has no compatible version?

### ISSUE THREAD

**Issue by firrae** [vsc55/ombi_sqlite_mysql#31]
When I try to install mysqlclient it fails with the error
```
ERROR: Could not find a version that satisfies the requirement mysqlclient (from versions: 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11rc1, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0, 1.4.1, 1.4.2, 1.4.2.post1, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0rc1, 2.1.0, 2.1.1)
ERROR: No matching distribution found for mysqlclient
```

```
python3 --version
Python 3.9.6

pip3 --version
pip 21.2.3 from /usr/lib64/python3.9/site-packages/pip (python 3.9)

python --version
Python 2.7.18
```

Any ideas on how to install other than just downgrading Python version (which wouldn't be very easy in my env).

**Comment by vsc55** [comment]
Hi @firrae,
In order not to touch the system that you currently have in Production, what I would do would be to create a Virtual Machine with a Debian 10 for the migration process.
What you would have to do is copy the ombi database files to the VM and run the guide on the virtual machine.
The only point that you would have to execute in the production machine would be point number 4.5, which is the creation of the tables and that is executed from Ombi. When you get to 4.5 putno copy the database.json file that has been generated in the VM and copy it to your production system, execute "/opt/ombi/Ombi --migrate" and then continue in the VM.

What system and version do you use?
