### ISSUE TITLE
Cannot Create Database.json Getting MYSQLDB Not Installed

### ISSUE THREAD

**Issue by gihayes** [vsc55/ombi_sqlite_mysql#33]
I am trying to migrate Ombi from SQLlite to MySQL and am having a problem creating Database.json. I have installed the full MySQL server and Workbench successfully and used the Create script via Workbench to create Ombi, Ombi_Settings, and Ombi_External databases and the user, ombi. I am running the latest version of Ombi. I downloaded the scripts and placed  ombi_sqlite2mysql.py and ombi_sqlite2mysql_multi.py into my Ombi directory. I have done the full (Everything) Python installation from the link in the migration instructions and indicated to add Python to path during the install successfully. I have shut down Ombi. I have checked Task Manager and both MySQL and Python are running. But when I run
 python ombi_sqlite2mysql.py -c C:\Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd O8888888* 
from within the Ombi directory, I get the following error:

 C:\Ombi>python ombi_sqlite2mysql.py -c C:\Ombi --only_db_json --host 127.0.0.1 --db Ombi --user ombi --passwd O88888888*
 Migration tool from SQLite to MySql/MariaDB for ombi (3.0.8) By VSC55

Error load MySQLdb, check if MySQLdb is installed!

C:\Ombi>

What am I doing wrong?
Thanks

**Comment by vsc55** [comment]
Hi @gihayes,
It seems that you are missing the python module that connects to mysql.
Try installing it with this command:
` pip3 install mysqlclient`
https://github.com/vsc55/ombi_sqlite_mysql?tab=readme-ov-file#3-download-script-and-install-dependencies

**Comment by gihayes** [comment]
Hello @vsc55 
Thank you for your advice! It worked. I was able to complete the migration!
 Thanks again
